language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get install -qq python-dev
# command to install dependencies
install: pip install -r requirements.txt --use-mirrors
# command to run tests
script: make build
after_success:
  - coveralls
